[package]
name = "madara_template"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs/" }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
